name: Gitee Pages Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install -g pnpm
        pnpm install
        
    - name: Build project
      run: pnpm run build
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        
    - name: Deploy to Gitee Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.GITEE_DEPLOY_KEY }}
        external_repository: Anti-noise/ai-investment
        publish_branch: gh-pages
        publish_dir: ./dist
        force_orphan: true
        
    - name: Notify deployment status
      run: |
        echo "Deployment completed successfully!"
        echo "Visit: https://${{ secrets.GITEE_USERNAME }}.gitee.io/ai-investment-website"